apiVersion: communityhub.europeanweather.cloud/v1alpha1
kind: CommunityHubCatalog
spec:
  items:
    ecmwf-data-flavour:
      name: "ecmwf-data-flavour"
      version: "1.0.0"
      description: |
        ECWF Data Flavor
        =======================================
        Includes the basic ECMWF software stack, with MARS client and an environment with `ecCodes`, `Metview`, `Earthkit` and `Aviso`.
        
        Getting started
        ---------------
        
        * Clone or download the code from the source repository.
        * Install ansible and other dependencies. You may want to do it in its own virtual environment (`pip install -r requirements.txt`)
        * Fetch the external requirements
          ```bash
          $ ansible-galaxy role install -r requirements.yml roles/
          ```
        
        * Define your inventory in `inventory`
        * Run the apropriate playbook 
        
          ```bash
          $ ansible-playbook -i inventory ecmwf-data-flavour.yml
          ```

        You may use the following ansible variables to customise this playbook:
        
        | Variable | Description | Type | Default | Required |
        |------|-------------|------|---------|----------|
        | reboot_if_required | Reboot the instance if required after an update. | `boolean`| `true` | no |
        | ecmwf_toolbox_env_wipe | Decide whether to wipe the environment if exists prior to a reinstallation. | `boolean` | `no` | no |
        | ecmwf_toolbox_env_wipe | Name of the environment containing the ECMWF toolbox. | `string` | `ecmwf-toolbox` | no |
        | ecmwf_toolbox_create_ipykernel | Create a system-wide kernel available. | `boolean` | yes | no |
        | conda_prefix | Prefix where conda is installed. | `string` | `/opt/conda` | no |
        | conda_user | User owning the conda installation. | `string` | `root` | no |
      
        Example usage:
      
        ```bash
        ansible-playbook -i inventory ecmwf-data-flavour.yml
        ```
        
        Author
        ------------------
        ECMWF for the European Weather Cloud
        
        <img src="https://climate.copernicus.eu/sites/default/files/inline-images/ECMWF.png"  width="120px" height="120px"> 
        
        ![ewc logo](https://europeanweather.cloud/sites/default/files/images/cloud-data-network-SW-v3.png){width=120px  height=120px}

      home: https://github.com/ewcloud/ewc-flavours
      sources:
        - https://github.com/ewcloud/ewc-flavours/blob/766090d57b3ad18d89f999e0601cb1fdf1e14eda/ecmwf-data-flavour.yml
      maintainers:
        - name: EWC Team
          email: support@ewcloud.int
          url: https://github.com/ewcloud/ewc-flavours/issues
      icon: https://raw.githubusercontent.com/ewcloud/ewc-community-hub/refs/heads/main/logos/EWC%20-%20Emblem%20color.png
      annotations:
        type: "Ansible Playbook"
        category: "Compute,Data Access"
        supportLevel: "EWC"
        licenseType: "Apache License 2.0"
      displayName: ECMWF Data Flavour
      summary: ECMWF's Data Flavour
      license: https://github.com/ewcloud/ewc-flavours/blob/main/LICENSE
      published: false
    ipa-server:
      name: "ipa-server"
      version: "1.0.0"
      description: |
        Centralized identity, authentication, and access management solution based on FreeIPA.
      home: https://github.com/ewcloud/ewc-flavours
      sources:
        - https://github.com/ewcloud/ewc-flavours/blob/main/ipa-server.yml
      maintainers:
        - name: EWC Team
          email: support@ewcloud.int
          url: https://github.com/ewcloud/ewc-flavours/issues
        - name: EWC Support Team
          email: testemail@ewcloud.int
          url: https://github.com/ewcloud/ewc-flavours/issues
      icon: https://raw.githubusercontent.com/ewcloud/ewc-community-hub/refs/heads/main/logos/EWC%20-%20Emblem%20color.png
      annotations:
        type: "Ansible Playbook"
        category: "Security,Identity & Access Management"
        supportLevel: "EWC"
        licenseType: "Apache License 2.0"
      displayName: FreeIPA
      summary: FreeIPA. Centralized identity, authentication, and access management solution based on FreeIPA.
      license: https://github.com/ewcloud/ewc-flavours/blob/main/LICENSE
      published: false
    jupyterhub-flavour:
      name: "jupyterhub-flavour"
      version: "1.0.0"
      description: |
        Installs and run  on your instance, offering a convenient way to access it through the web.
      home: https://github.com/ewcloud/ewc-flavours
      sources:
        - https://github.com/ewcloud/ewc-flavours/blob/d9948e334735e129a1c869cee865d5c42912a332/jupyterhub-flavour.yml
      maintainers:
        - name: EWC Team
          email: support@ewcloud.int
          url: https://github.com/ewcloud/ewc-flavours/issues
      icon: https://raw.githubusercontent.com/ewcloud/ewc-community-hub/refs/heads/main/logos/EWC%20-%20Emblem%20color.png
      annotations:
        type: "Ansible Playbook"
        category: "Compute,Data Visualization,Data Processing"
        supportLevel: "EWC"
        licenseType: "Apache License 2.0"
      displayName: JupyterHub Flavour
      summary: JupyterHub flavour. It installs and run jupyterhub on your instance, offering a convenient way to access it through the web.
      license: https://github.com/ewcloud/ewc-flavours/blob/main/LICENSE
      published: false
    openstack-compute:
      name: "openstack-compute"
      version: "1.0.0"
      description: |
        Pre-configured instance for deploying and managing OpenStack compute resources using Terraform.
      home: https://github.com/ewcloud/openstack-compute
      sources:
        - https://github.com/ewcloud/openstack-compute
      maintainers:
        - name: EWC Team
          email: support@ewcloud.int
          url: https://github.com/ewcloud/openstack-compute/issues
      icon: https://raw.githubusercontent.com/ewcloud/ewc-community-hub/refs/heads/main/logos/EWC%20-%20Emblem%20color.png
      annotations:
        type: "Terraform Module"
        category: "Compute"
        supportLevel: "EWC"
        licenseType: "Apache License 2.0"
      displayName: Openstack Compute
      summary: Openstack compute Terraform Module. Pre-configured instance for deploying and managing OpenStack compute resources using Terraform.
      license: https://github.com/ewcloud/openstack-compute/blob/main/LICENSE
      published: false
    remote-desktop:
      name: "remote-desktop"
      version: "1.0.0"
      description: |
        Virtual desktop instance providing remote graphical access to applications and development environments.
      home: https://github.com/ewcloud/ewc-flavours
      sources:
        - https://github.com/ewcloud/ewc-flavours/blob/main/remote-desktop.yml
      maintainers:
        - name: EWC Team
          email: support@ewcloud.int
          url: https://github.com/ewcloud/ewc-flavours/issues
        - name: EWC Support Team
          email: testemail@ewcloud.int
          url: https://github.com/ewcloud/ewc-flavours/issues
      icon: https://raw.githubusercontent.com/ewcloud/ewc-community-hub/refs/heads/main/logos/EWC%20-%20Emblem%20color.png
      annotations:
        type: "Ansible Playbook"
        category: "Remote Access & Desktop"
        supportLevel: "EWC"
        licenseType: "Apache License 2.0"
      displayName: Remote Desktop
      summary: Remote Desktop. Virtual desktop instance providing remote graphical access to applications and development environments.
      license: https://github.com/ewcloud/ewc-flavours/blob/main/LICENSE
      published: false
    ssh-bastion:
      name: "ssh-bastion"
      version: "1.0.0"
      description: |
        Create secure SSH Bastion host providing controlled, audited access to private network resources.
      home: https://github.com/ewcloud/ewc-flavours
      sources:
        - https://github.com/ewcloud/ewc-flavours/blob/main/ssh-bastion.yml
      maintainers:
        - name: EWC Team
          email: support@ewcloud.int
          url: https://github.com/ewcloud/ewc-flavours/issues
        - name: EWC Support Team
          email: testemail@ewcloud.int
          url: https://github.com/ewcloud/ewc-flavours/issues
      icon: https://raw.githubusercontent.com/ewcloud/ewc-community-hub/refs/heads/main/logos/EWC%20-%20Emblem%20color.png
      annotations:
        type: "Ansible Playbook"
        category: "Networking,Security,Access Management"
        supportLevel: "EWC"
        licenseType: "Apache License 2.0"
      displayName: SSH Bastion
      summary: SSH Bastion. Create secure SSH Bastion host providing controlled, audited access to private network resources.
      license: https://github.com/ewcloud/ewc-flavours/blob/main/LICENSE
      published: false