apiVersion: communityhub.europeanweather.cloud/v1alpha1
kind: CommunityHubCatalog
spec:
  items:
    ecmwf-data-flavour:
      name: "ecmwf-data-flavour"
      version: "1.0.0"
      description: |
        ECMWF Data Flavour: includes the basic ECMWF software stack, with MARS client and an environment with ecCodes, Metview, Earthkit and Aviso.
      home: https://github.com/ewcloud/ewc-flavours
      sources:
        - https://github.com/ewcloud/ewc-flavours/blob/766090d57b3ad18d89f999e0601cb1fdf1e14eda/ecmwf-data-flavour.yml
      maintainers:
        - name: EWC Team
          email: support@ewcloud.int
          url: https://github.com/ewcloud/ewc-flavours/issues
      icon: https://github.com/ewcloud/ewc-community-hub/blob/53620693e2a3552371d28128d05c851da61e2b21/logos/EWC%20-%20Emblem%20color.png
      annotations:
        type: "Virtual Machines"
        category: "Ansible Playbook"
        supportLevel: "EWC"
        licenseType: "Apache License 2.0"
      displayName: ECMWF Data Flavour
      summary: ECMWF's Data Flavour
      license: https://github.com/ewcloud/ewc-flavours/blob/main/LICENSE
      published: false
    jupyterhub-flavour:
      name: "jupyterhub-flavour"
      version: "1.0.0"
      description: |
        Installs and run jupyterhub on your instance, offering a convenient way to access it through the web.
      home: https://github.com/ewcloud/ewc-flavours
      sources:
        - https://github.com/ewcloud/ewc-flavours/blob/d9948e334735e129a1c869cee865d5c42912a332/jupyterhub-flavour.yml
      maintainers:
        - name: EWC Team
          email: support@ewcloud.int
          url: https://github.com/ewcloud/ewc-flavours/issues
      icon: https://github.com/ewcloud/ewc-community-hub/blob/53620693e2a3552371d28128d05c851da61e2b21/logos/EWC%20-%20Emblem%20color.png
      annotations:
        type: "Virtual Machines"
        category: "Ansible Playbook"
        supportLevel: "EWC"
        licenseType: "Apache License 2.0"
      displayName: JupyterHub Flavour
      summary: JupyterHub flavour
      license: https://github.com/ewcloud/ewc-flavours/blob/main/LICENSE
      published: false
