name: Nightly Ansible Deployments Testing

on:
  schedule:
    - cron: "0 3 0 0 1-5"
      timezone: "Etc/UTC"

env:
  POLLING_INTERVAL_SECONDS: 60
  RUN_TIMEOUT_MINUTES: 20 # Max runtime per each downstream workflow run
  MAX_CONCURRENT_WORKFLOWS: 1
jobs:
  test-deploy-ansible-ecmwf:
    name: Ansible Playbook Testing (Native) on ECMWF
    runs-on: ubuntu-latest
    timeout-minutes: 200
    environment: ECMWF
    needs: lint

    steps:
      - name: Generate installation token for EWC Community Hub CI Orchestrator GitHub App
        id: app-token
        uses: actions/create-github-app-token@v3
        with:
          client-id: ${{ vars.EWC_COMMUNITY_HUB_CI_ORCHESTRATOR_CLIENT_ID }}
          private-key: ${{ secrets.EWC_COMMUNITY_HUB_CI_ORCHESTRATOR_PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}

      - name: Checkout catalog repository
        uses: actions/checkout@v6

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: 3.12

      - name: Install additional dependencies
        run: pip install -r .github/scripts/orchestrator/requirements.txt

      - name: Orchestrate deployments testing
        run: python .github/scripts/orchestrator/main.py
        env:
          GH_API_TOKEN: ${{ steps.app-token.outputs.token }}
          ITEM_TECHNOLOGY_ANNOTATIONS: "Ansible Playbook"
          ITEM_OTHERS_ANNOTATIONS: "Deployable"
          GH_DOWNSTREAM_WORKFLOW_FILE: "test-ecmwf.yml"
          TOTAL_TIMEOUT_MINUTES: 190 # Must be smaller than jobs.orchestrate.timeout-minutes
  
  test-deploy-ansible-eumetsat:
    name: Ansible Playbook Testing (Native) on EUMETSAT
    runs-on: ubuntu-latest
    timeout-minutes: 300
    environment: EUMETSAT
    needs: lint

    steps:
      - name: Generate installation token for EWC Community Hub CI Orchestrator GitHub App
        id: app-token
        uses: actions/create-github-app-token@v3
        with:
          client-id: ${{ vars.EWC_COMMUNITY_HUB_CI_ORCHESTRATOR_CLIENT_ID }}
          private-key: ${{ secrets.EWC_COMMUNITY_HUB_CI_ORCHESTRATOR_PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}

      - name: Checkout catalog repository
        uses: actions/checkout@v6

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: 3.12

      - name: Install additional dependencies
        run: pip install -r .github/scripts/orchestrator/requirements.txt

      - name: Orchestrate deployments testing
        run: python .github/scripts/orchestrator/main.py
        env:
          GH_API_TOKEN: ${{ steps.app-token.outputs.token }}
          ITEM_TECHNOLOGY_ANNOTATIONS: "Ansible Playbook"
          ITEM_OTHERS_ANNOTATIONS: "Deployable"
          GH_DOWNSTREAM_WORKFLOW_FILE: "test-eumetsat.yml"
          TOTAL_TIMEOUT_MINUTES: 290 # Must be smaller than jobs.orchestrate.timeout-minutes

  test-deploy-ansible-ecmwf-via-ewccli:
    name: Ansible Playbook Testing (via EWCCLI) on ECMWF
    runs-on: ubuntu-latest
    timeout-minutes: 200
    environment: ECMWF
    needs: lint

    steps:
      - name: Generate installation token for EWC Community Hub CI Orchestrator GitHub App
        id: app-token
        uses: actions/create-github-app-token@v3
        with:
          client-id: ${{ vars.EWC_COMMUNITY_HUB_CI_ORCHESTRATOR_CLIENT_ID }}
          private-key: ${{ secrets.EWC_COMMUNITY_HUB_CI_ORCHESTRATOR_PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}

      - name: Checkout catalog repository
        uses: actions/checkout@v6

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: 3.12

      - name: Install additional dependencies
        run: pip install -r .github/scripts/orchestrator/requirements.txt

      - name: Orchestrate deployments testing
        run: python .github/scripts/orchestrator/main.py
        env:
          GH_API_TOKEN: ${{ steps.app-token.outputs.token }}
          ITEM_TECHNOLOGY_ANNOTATIONS: "Ansible Playbook"
          ITEM_OTHERS_ANNOTATIONS: "Deployable,EWCCLI-compatible"
          GH_DOWNSTREAM_WORKFLOW_FILE: "test-deployment-ansible-ecmwf.yml"
          TOTAL_TIMEOUT_MINUTES: 190 # Must be smaller than jobs.orchestrate.timeout-minutes
          EXCLUDED_ITEM_NAMES: "xcube-viewer-flavour,eumetcast-terrestrial-amt-flavour,ipa-server-flavour"

  test-deploy-ansible-eumetsat-via-ewccli:
    name: Ansible Playbook Testing (via EWCCLI) on EUMETSAT
    runs-on: ubuntu-latest
    timeout-minutes: 300
    environment: EUMETSAT
    needs: lint

    steps:
      - name: Generate installation token for EWC Community Hub CI Orchestrator GitHub App
        id: app-token
        uses: actions/create-github-app-token@v3
        with:
          client-id: ${{ vars.EWC_COMMUNITY_HUB_CI_ORCHESTRATOR_CLIENT_ID }}
          private-key: ${{ secrets.EWC_COMMUNITY_HUB_CI_ORCHESTRATOR_PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}

      - name: Checkout catalog repository
        uses: actions/checkout@v6

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: 3.12

      - name: Install additional dependencies
        run: pip install -r .github/scripts/orchestrator/requirements.txt

      - name: Orchestrate deployments testing
        run: python .github/scripts/orchestrator/main.py
        env:
          GH_API_TOKEN: ${{ steps.app-token.outputs.token }}
          ITEM_TECHNOLOGY_ANNOTATIONS: "Ansible Playbook"
          ITEM_OTHERS_ANNOTATIONS: "Deployable,EWCCLI-compatible"
          GH_DOWNSTREAM_WORKFLOW_FILE: "test-deployment-ansible-eumetsat.yml"
          TOTAL_TIMEOUT_MINUTES: 290 # Must be smaller than jobs.orchestrate.timeout-minutes
          EXCLUDED_ITEM_NAMES: "xcube-viewer-flavour,eumetcast-terrestrial-amt-flavour,ipa-server-flavour"
