name: Validation

on:
  pull_request:
    branches:
      - "main"

env:
  POLLING_INTERVAL_SECONDS: 60
  RUN_TIMEOUT_MINUTES: 20 # Max runtime per each downstream workflow run
  MAX_CONCURRENT_WORKFLOWS: 1
jobs:
  lint:
    name: Metadata Linting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24

      - name: Install Node dependencies
        run: npm install -g ajv-cli

      - name: Validate items metadata styling
        run: |
          char_count_before_trim=$(cat items.yaml | wc -m)
          
          sed -i 's/[[:space:]]*$//' items.yaml

          char_count_after_trim=$(cat items.yaml | wc -m)
          char_count_diff=$(( $char_count_before_trim - $char_count_after_trim ))

          if [[ "$char_count_diff" -gt "0" ]]; then
              echo "items.yaml contains ${char_count_diff} trailing space(s) that Must be trimmed"
              exit 1
          fi

      - name: Validate items metadata serialization
        run: |
          yq -o=json "items.yaml" > "items.json"

      - name: Validate items metadata contents
        run: |
          ajv validate -s schemas/items/v1alpha1.json -d items.json --spec=draft2020
